ARG NODE_VERSION=20

FROM node:${NODE_VERSION}-alpine AS base
RUN corepack enable && corepack prepare pnpm@9.7.0 --activate
RUN apk add --no-cache openssl1.1-compat || apk add --no-cache openssl
WORKDIR /app

COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY tsconfig.base.json ./

COPY packages/prisma/package.json ./packages/prisma/package.json
COPY apps/api/package.json ./apps/api/package.json
COPY apps/web/package.json ./apps/web/package.json
RUN pnpm install --no-frozen-lockfile

COPY apps/api ./apps/api
COPY packages/prisma ./packages/prisma

EXPOSE 4000
WORKDIR /app
CMD ["sh","-lc","pnpm --dir apps/api start:dev"]
